
############################################################
# Clock Period Constraints                                 #
############################################################







set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWREN_tri_io[0]}]

set_property PACKAGE_PIN V10 [get_ports {PWREN_tri_io[6]}]
set_property PACKAGE_PIN P15 [get_ports {PWREN_tri_io[5]}]
set_property PACKAGE_PIN N15 [get_ports {PWREN_tri_io[4]}]
set_property PACKAGE_PIN N16 [get_ports {PWREN_tri_io[3]}]
set_property PACKAGE_PIN R19 [get_ports {PWREN_tri_io[2]}]
set_property PACKAGE_PIN T19 [get_ports {PWREN_tri_io[1]}]
set_property PACKAGE_PIN F20 [get_ports {PWREN_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ADC_B_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_B_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_B_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_spi_ncs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_A_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_A_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_A_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_spi_ncs[0]}]

set_input_delay -clock [get_clocks clk_fpga_0] -min -add_delay 15.000 [get_ports ADC_A_spi_miso]
set_input_delay -clock [get_clocks clk_fpga_0] -max -add_delay 15.000 [get_ports ADC_A_spi_miso]
set_input_delay -clock [get_clocks clk_fpga_0] -min -add_delay 15.000 [get_ports ADC_B_spi_miso]
set_input_delay -clock [get_clocks clk_fpga_0] -max -add_delay 15.000 [get_ports ADC_B_spi_miso]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports ADC_A_spi_clk]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports ADC_A_spi_clk]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports ADC_A_spi_mosi]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports ADC_A_spi_mosi]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports {ADC_A_spi_ncs[0]}]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports {ADC_A_spi_ncs[0]}]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports ADC_B_spi_clk]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports ADC_B_spi_clk]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports ADC_B_spi_mosi]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports ADC_B_spi_mosi]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 10.000 [get_ports {ADC_B_spi_ncs[0]}]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 10.000 [get_ports {ADC_B_spi_ncs[0]}]


set_property PACKAGE_PIN Y9 [get_ports ADC_B_spi_miso]
set_property PACKAGE_PIN Y8 [get_ports ADC_B_spi_mosi]
set_property PACKAGE_PIN Y6 [get_ports {ADC_B_spi_ncs[0]}]
set_property PACKAGE_PIN T9 [get_ports ADC_A_spi_miso]
set_property PACKAGE_PIN U10 [get_ports ADC_A_spi_mosi]
set_property PACKAGE_PIN V7 [get_ports {ADC_A_spi_ncs[0]}]
set_property PACKAGE_PIN Y7 [get_ports ADC_B_spi_clk]
set_property PACKAGE_PIN U7 [get_ports ADC_A_spi_clk]

set_property SLEW FAST [get_ports ADC_B_spi_clk]
set_property SLEW FAST [get_ports ADC_A_spi_clk]
set_property SLEW FAST [get_ports {ADC_A_spi_ncs[0]}]
set_property SLEW FAST [get_ports ADC_A_spi_mosi]
set_property SLEW FAST [get_ports ADC_B_spi_mosi]
set_property SLEW FAST [get_ports {ADC_B_spi_ncs[0]}]

set_property PACKAGE_PIN V5 [get_ports {PL_LEDS[0]}]
set_property PACKAGE_PIN V8 [get_ports {PL_LEDS[1]}]

set_property PACKAGE_PIN F16 [get_ports {ATCA_LEDS[0]}]
set_property PACKAGE_PIN F17 [get_ports {ATCA_LEDS[1]}]
set_property PACKAGE_PIN D18 [get_ports {ATCA_LEDS[2]}]
set_property PACKAGE_PIN D19 [get_ports {ATCA_LEDS[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports {PL_LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PL_LEDS[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ATCA_LEDS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ATCA_LEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ATCA_LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ATCA_LEDS[0]}]

set_property PACKAGE_PIN B20 [get_ports TCK]
set_property IOSTANDARD LVCMOS33 [get_ports TCK]
set_property SLEW FAST [get_ports TCK]
set_property PACKAGE_PIN E17 [get_ports TDI]
set_property IOSTANDARD LVCMOS33 [get_ports TDI]
set_property SLEW FAST [get_ports TDI]
set_property PACKAGE_PIN A20 [get_ports TDO]
set_property IOSTANDARD LVCMOS33 [get_ports TDO]
set_property PACKAGE_PIN B19 [get_ports TMS]
set_property IOSTANDARD LVCMOS33 [get_ports TMS]

set_property SLEW FAST [get_ports TMS]
set_property DRIVE 12 [get_ports TCK]

set_property IOSTANDARD LVCMOS33 [get_ports PIM400_I2C_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports PIM400_I2C_sda_io]
set_property PACKAGE_PIN H15 [get_ports PIM400_I2C_scl_io]
set_property PACKAGE_PIN H17 [get_ports PIM400_I2C_sda_io]
set_property PACKAGE_PIN J18 [get_ports EEPROM_I2C_scl_io]
set_property PACKAGE_PIN J20 [get_ports EEPROM_I2C_sda_io]

set_property PACKAGE_PIN L17 [get_ports ESM_UART_rxd]
set_property PACKAGE_PIN L19 [get_ports ESM_UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports ESM_UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports ESM_UART_txd]

set_property PACKAGE_PIN G20 [get_ports HNDL_SW]
set_property IOSTANDARD LVCMOS33 [get_ports HNDL_SW]

set_property PACKAGE_PIN G15 [get_ports {ESM_RESET_tri_o[0]}]
set_property PACKAGE_PIN H16 [get_ports {ESM_RESET_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ESM_RESET_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ESM_RESET_tri_o[0]}]
set_property OFFCHIP_TERM NONE [get_ports ESM_RESET_tri_o[1]]
set_property OFFCHIP_TERM NONE [get_ports ESM_RESET_tri_o[0]]
set_property PACKAGE_PIN K19 [get_ports {ESM_FLASH_SPI_ss_io[0]}]
set_property PACKAGE_PIN H20 [get_ports ESM_FLASH_SPI_sck_io]
set_property PACKAGE_PIN G14 [get_ports ESM_FLASH_SPI_io0_io]
set_property PACKAGE_PIN J15 [get_ports ESM_FLASH_SPI_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports {ESM_FLASH_SPI_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ESM_FLASH_SPI_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports ESM_FLASH_SPI_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports ESM_FLASH_SPI_sck_io]
set_property SLEW FAST [get_ports {ESM_FLASH_SPI_ss_io[0]}]
set_property SLEW FAST [get_ports ESM_FLASH_SPI_io0_io]
set_property SLEW FAST [get_ports ESM_FLASH_SPI_io1_io]
set_property SLEW FAST [get_ports ESM_FLASH_SPI_sck_io]

set_property PACKAGE_PIN G15 [get_ports {ESM_RESET_tri_io[0]}]
set_property PACKAGE_PIN H16 [get_ports {ESM_RESET_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ESM_RESET_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ESM_RESET_tri_io[0]}]
set_property PACKAGE_PIN K18 [get_ports ELM_UART_rxd]
set_property PACKAGE_PIN K17 [get_ports ELM_UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports ELM_UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports ELM_UART_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {ELM_BOOT_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ELM_BOOT_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ELM_LINK_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ELM_LINK_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ELM_LINK_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ELM_LINK_tri_io[0]}]
set_property PACKAGE_PIN K14 [get_ports {ELM_LINK_tri_io[0]}]
set_property PACKAGE_PIN L20 [get_ports {ELM_LINK_tri_io[1]}]
set_property PACKAGE_PIN L16 [get_ports {ELM_LINK_tri_io[2]}]
set_property PACKAGE_PIN L14 [get_ports {ELM_LINK_tri_io[3]}]
set_property PACKAGE_PIN R17 [get_ports {ELM_BOOT_tri_io[0]}]
set_property PACKAGE_PIN R18 [get_ports {ELM_BOOT_tri_io[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_I2C_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_I2C_sda_io]

set_property OFFCHIP_TERM NONE [get_ports ADC_A_spi_clk]
set_property OFFCHIP_TERM NONE [get_ports ADC_A_spi_mosi]
set_property OFFCHIP_TERM NONE [get_ports ADC_B_spi_clk]
set_property OFFCHIP_TERM NONE [get_ports ADC_B_spi_mosi]
set_property OFFCHIP_TERM NONE [get_ports EEPROM_I2C_scl_io]
set_property OFFCHIP_TERM NONE [get_ports EEPROM_I2C_sda_io]
set_property OFFCHIP_TERM NONE [get_ports ELM_UART_txd]
set_property OFFCHIP_TERM NONE [get_ports ESM_FLASH_SPI_io0_io]
set_property OFFCHIP_TERM NONE [get_ports ESM_FLASH_SPI_io1_io]
set_property OFFCHIP_TERM NONE [get_ports ESM_FLASH_SPI_sck_io]
set_property OFFCHIP_TERM NONE [get_ports ESM_UART_txd]
set_property OFFCHIP_TERM NONE [get_ports PIM400_I2C_scl_io]
set_property OFFCHIP_TERM NONE [get_ports PIM400_I2C_sda_io]
set_property OFFCHIP_TERM NONE [get_ports TCK]
set_property OFFCHIP_TERM NONE [get_ports TDI]
set_property OFFCHIP_TERM NONE [get_ports TMS]
set_property OFFCHIP_TERM NONE [get_ports ADC_A_spi_ncs[0]]
set_property OFFCHIP_TERM NONE [get_ports ADC_B_spi_ncs[0]]
set_property OFFCHIP_TERM NONE [get_ports ATCA_LEDS[3]]
set_property OFFCHIP_TERM NONE [get_ports ATCA_LEDS[2]]
set_property OFFCHIP_TERM NONE [get_ports ATCA_LEDS[1]]
set_property OFFCHIP_TERM NONE [get_ports ATCA_LEDS[0]]
set_property OFFCHIP_TERM NONE [get_ports ELM_BOOT_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports ELM_BOOT_tri_io[0]]
set_property OFFCHIP_TERM NONE [get_ports ELM_LINK_tri_io[3]]
set_property OFFCHIP_TERM NONE [get_ports ELM_LINK_tri_io[2]]
set_property OFFCHIP_TERM NONE [get_ports ELM_LINK_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports ELM_LINK_tri_io[0]]
set_property OFFCHIP_TERM NONE [get_ports ESM_FLASH_SPI_ss_io[0]]
set_property OFFCHIP_TERM NONE [get_ports ESM_RESET_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports ESM_RESET_tri_io[0]]
set_property OFFCHIP_TERM NONE [get_ports PL_LEDS[1]]
set_property OFFCHIP_TERM NONE [get_ports PL_LEDS[0]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[6]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[5]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[4]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[3]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[2]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports PWREN_tri_io[0]]
